### ISSUE TITLE
Can't open files on Windows 10

### ISSUE THREAD

**Issue by kingjon3377** [kingjon3377/strategicprimer-viewer#22]
A user reports that, on Windows 10, he can open the "app chooser" and choose a file, but he sees no effect of that at all. Running from the Command Prompt, and even specifying the file and/or the app there, also has no effect---and shows no output there.

**Comment by kingjon3377** [comment]
Hoping for useful debugging information, I tested it in Eclipse on Windows 7, and could not reproduce it there; both the "run as Ceylon Java Application" and the "fat JAR" option worked fine. Either something has changed between Windows 7 and Windows 10, or there's something wrong with how it's getting invoked via Launch4J, or something *very* strange is going on.

**Comment by kingjon3377** [comment]
I think I just saw a similar thing when adding tracing logging to the app, on Mac OS X. So it may not even be OS-dependent, just a Heisenbug.

**Comment by kingjon3377** [comment]
Or maybe not; it appears it was just being slow and I wasn't being patient enough there. Hmm.

**Comment by kingjon3377** [comment]
There are two problems confounding each other here: the first is that Launch4J, which we use to wrap the JAR into a Windows EXE, by default daemonizes the process and disconnects standard input, output, and error from the Command Prompt, and the second is a totally spurious "map format error" with the following stack-trace:

```
Exception in thread "AWT-EventQueue-0" strategicprimer.drivers.common.DriverFailedException "SP map format error"
        at strategicprimer.drivers.common.mapReaderAdapter_.readMapModel(map_reader_adapter.ceylon:47)
        at strategicprimer.drivers.common.SimpleDriver$impl.startDriverOnArguments$canonical$(interfaces.ceylon:254)
        at strategicprimer.drivers.common.SimpleDriver$impl.startDriverOnArguments(interfaces.ceylon:109)
        at strategicprimer.viewer.drivers.worker_mgmt.workerGUI_.startDriverOnArguments(workerGUI.ceylon)
        at strategicprimer.viewer.drivers.appChooserFrame_$1buttonHandler_.buttonHandler(drivers.ceylon:463)
        at strategicprimer.viewer.drivers.appChooserFrame_$3.$call$(drivers.ceylon:473)
        at lovelace.util.jvm.listenedButton_$1.$call$(common_controls.ceylon:52)
        at lovelace.util.jvm.listenedButton_$1.actionPerformed(common_controls.ceylon)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: strategicprimer.model.xmlio.exceptions.UnwantedChildException "Incorrect SP XML at line 2822, column 56: Unexpected child Skill in tag job"
        at strategicprimer.model.xmlio.fluidxml.unitMemberHandler_.readJob(unit_members.ceylon:84)
        at strategicprimer.model.xmlio.fluidxml.unitMemberHandler_.readWorker(unit_members.ceylon:60)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader$1$27.$call$(SPFluidReader.ceylon:458)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader$1$27.$call$(SPFluidReader.ceylon:458)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.readSPObject$priv$(SPFluidReader.ceylon:123)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.readUnit$priv$(SPFluidReader.ceylon:373)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.access$200(SPFluidReader.ceylon:110)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader$1$31.$call$(SPFluidReader.ceylon:462)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader$1$31.$call$(SPFluidReader.ceylon:462)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.readSPObject$priv$(SPFluidReader.ceylon:123)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.readFortress$priv$(SPFluidReader.ceylon:418)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.access$300(SPFluidReader.ceylon:110)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader$1$32.$call$(SPFluidReader.ceylon:463)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader$1$32.$call$(SPFluidReader.ceylon:463)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.readSPObject$priv$(SPFluidReader.ceylon:123)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.parseTileChild$priv$(SPFluidReader.ceylon:180)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.parseTile$priv$(SPFluidReader.ceylon:218)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.readMapOrViewTag$priv$(SPFluidReader.ceylon:269)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.access$400(SPFluidReader.ceylon:110)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader$1$38.$call$(SPFluidReader.ceylon:473)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader$1$38.$call$(SPFluidReader.ceylon:471)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.readSPObject$priv$(SPFluidReader.ceylon:123)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.readXML(SPFluidReader.ceylon:496)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.readMapFromStream(SPFluidReader.ceylon:510)
        at strategicprimer.model.xmlio.fluidxml.SPFluidReader.readMap(SPFluidReader.ceylon:506)
        at strategicprimer.model.xmlio.mapIOHelper_.readMap$canonical$(map_reader_adapter.ceylon:50)
        at strategicprimer.model.xmlio.mapIOHelper_.readMap(map_reader_adapter.ceylon:46)
        at strategicprimer.drivers.common.mapReaderAdapter_.readMapModel(map_reader_adapter.ceylon:40)
        ... 43 more
```
